ASP.net/Models/Car.cs

namespace ASP.net.Models{

    public class Car{
        public int Id {get; set;}

        public decimal DailyPrice {get; set;}

        public string Make {get; set;}

        public string Model {get; set;}

        public int Year {get; set;}

        public string PassengerCapacity {get; set;}

        public string Mileage {get; set;}

        public string ImageUrl {get; set;}

        public string HP {get; set;}

        public string Cyls {get; set;}

        public string Description {get; set;}

        public string Doors {get; set;}
    }
}

ASP.net/Models/DataContext.cs

using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;

namespace ASP.net.Models{
    /*
    represents the connection with the DB
    will be used to access the different tables (classes)
    to retrieve and store information/records
    */
    public class DataContext : DbContext{
        
         public DataContext(DbContextOptions<DataContext> options) : base(options)
         {

         }

         // specify which model requires to be a table in the DB

         public DbSet<Car> Cars {get; set;}

    }
}

ASP.net/Models/ErrorViewModel.cs
using System;

namespace ASP.net.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.net/Controllers/CatalogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ASP.net.Models;  

namespace ASP.net.Controllers
{
    public class CatalogController : Controller {

        private DataContext dbContext;

        // class constructor
        public CatalogController(DataContext context){
            this.dbContext = context;
        }
        // derfault page
        // to show the catalog of CARS available to rent
        public IActionResult Index(){
            return View();
        }

        public IActionResult Register(){
            return View();
        }

        [HttpPost]
        public IActionResult SaveCar( [FromBody] Car theCar){
            
            dbContext.Cars.Add(theCar); // add the car to the table
            dbContext.SaveChanges(); // save changes

            return Json(theCar); // return the car
        }

        [HttpGet]
        public IActionResult GetCatalog(){
            var carList = dbContext.Cars.ToList(); // retrieve all records from the table
            return Json(carList);
        }
        // register form
        // .... Ms Sql Server
    }
}

ASP.net/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ASP.net.Models;

namespace ASP.net.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Test(){
            return View();
        }

         public IActionResult About(){
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.net/Views/Catalog/Index.cshtml

@{
    ViewData["Title"] = "Cars Catalog";
}

@section Styles{
    <link href="~/css/catalog.css" rel="stylesheet">
}

@section Scripts{
    <script src="~/js/catalog.js"></script>
}


<h1>Cars For Rent</h1>

<div id="catalogContainer" class="row">



</div>

ASP.net/Views/Catalog/Register.cshtml
@section Styles{
    <link href="~/css/register.css" rel="stylesheet">
}

@section Scripts{
    <script src="~/js/register.js"></script>
}

<div id="errorAlert" class="alert alert-danger">
    Fix error(s) below to continue

</div>

<div id="savedAlert" class="alert alert-success">
    Car is registerd!

</div>


<div class="container register">
<div class="row">
    <div class="col-md-3 register-left">
        <h1>Register New Car</h1>
    </div>
    <div class="col-md-9 register-right">
                <div class="row register-form">
                    <div class="col-md-6">
                        <div class="form-group">
                            <h5>Price</h5><input type="number" class="form-control" placeholder="Daily Price *" id=txtPrice />
                        </div>
                        <div class="form-group">
                            <h5>Make</h5><input type="text" class="form-control" placeholder="Make of the car *" id=txtMake />
                        </div>
                        <div class="form-group">
                            <h5>Model</h5><input type="text" class="form-control" placeholder="Model of the Car *" id="txtModel" />
                        </div>
                        <div class="form-group">
                            <h5>Year</h5><input type="number" class="form-control"  placeholder="Year of the Car *" id="txtYear" />
                        </div>
                        <div class="form-group">
                            <h5>Seat Capacity</h5><input type="number" class="form-control" placeholder="Number of seat Capacity *" id="txtCapacity" />
                        </div>
                    </div>
                    <div class="col-md-6">
                         <div class="form-group">
                            <h5>Milage</h5><input type="number" placeholder="Milage of the Vehicle" class="form-control" id="txtMileage" />
                        </div>
                        <div class="form-group">
                            <h5>Image Url</h5><input type="text" placeholder="Images of vehicle" class="form-control" id="txtImageUrl" />
                        </div>
                        <div class="form-group">
                            <h5>Horse Power</h5><input type="number" class="form-control" placeholder="Horse Power *" id=txtHP />
                        </div>
                        <div class="form-group">
                            <h5>Cylinders</h5><input type="number" class="form-control" placeholder="Number of cylinders *" id=txtCyls />
                        </div>
                        <div class="form-group">
                            <h5>Description</h5><input type="text" class="form-control" placeholder="Quick Description *" id=txtDescription />
                        </div>
                        <button type="button" class="btnRegister"  id="btnSave">Save Car</button>
                    </div>
                </div>
    </div>
</div>
</div>


ASP.net/Views/Home/About.cshtml
<h1>My name: Rhenard</h1>

ASP.net/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@section Styles{
    <link href="~/css/home.css" rel="stylesheet">
}

<div class="text-center">
    <div>
        <p>Skip the rental counter</p>
        <h2 class="renterPlacementTrust-sectionTitle h3">We have what you need made easy!</h2>
        <div class="grid">
            <div class="grid-item grid-item--6 grid-item--medium6 grid-item--small6 grid-item--xsmall12">
                <div>
                    <div>
                        <img class="js-lazyLoad" width="48" height="48" src="https://d84g7x7n0gri.cloudfront.net/img/home/ic-car-photos.c09bd3b5.png" style="overflow: hidden;">
                    </div>
                    <div class="renterPlacementTrust-text">
                            <p class="renterPlacementTrust-title">Endless options

                            </p>
                            <p class="renterPlacementTrust-description">Choose from hundreds of models you won’t find anywhere else. Pick it up or get it delivered where you want it.</p>
                            <p></p>
                    </div>
                    <div class="grid-item grid-item--6 grid-item--medium6 grid-item--small6 grid-item--xsmall12">
                        <div class="renterPlacementTrust-item">
                            <div class="renterPlacementTrust-image">
                                <img class="js-lazyLoad" width="49" height="46" src="https://d84g7x7n0gri.cloudfront.net/img/home/ic-thumbs-up.b102fc90.png" style="overflow: hidden;">
                            </div>
                            <div class="renterPlacementTrust-text">
                                <p class="renterPlacementTrust-title">Insurance options included</p>
                                <p class="renterPlacementTrust-description">Drive confidently with your choice of protection plans — all plans include varying levels of liability insurance from Liberty Mutual provided through Turo Insurance Agency and physical damage protection.

                                </p><p></p>
                            </div>
                        </div>
                    </div>
                </div>
                            <div>
                                <a class="nav-link text-dark bookBtn" asp-area="" asp-controller="Catalog" asp-action="Index">Book The Perfect Car</a>
                            </div>
</div>
</div>

ASP.net/Views/Home/Test.cshtml
@{

}

<h1>Test Page</h1>
<p></p>

ASP.net/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.net</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ASP.net</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                         <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Catalog
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Index">Cars for rent</a>
                            <a class="nav-link text-dark" asp-area="" asp-controller="Catalog" asp-action="Register">Register</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ASP.net - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>